import { Base } from "@stratamu/base"
import type { Engine } from "@stratamu/engine-core"
import type { Session } from "@stratamu/engine-sessions"
import { isDefined } from "@stratamu/guards"
import { type EntityId, sessionId } from "@stratamu/primitives"

import type { AberMUDAdapter } from "../adapter.ts"
import type { AberOutput } from "../output.ts"
import { renderOutput } from "../output.ts"
import type { AberMUDLoginConnection } from "./login-connection.ts"

/**
 * The Name/Password login flow, and the hand-off from it into ordinary game input.
 *
 * Deliberately out of scope:
 * - New-character creation. `AberMUDAdapter.login` needs a `sex` only for a brand-new character;
 *   this always passes `0` rather than prompting for it, so login only actually works for a name
 *   with an existing persona. Interactive character creation is a separate, larger flow.
 * - A retry limit. A wrong password reprompts for a name indefinitely; a real server would want
 *   a limit and a disconnect.
 * - Any wording beyond "Name:"/"Password:"/"Login incorrect."; a real front end's prompts are a
 *   presentation concern, same as `AberOutput`'s `renderOutput`.
 */
export interface AberMUDLoginOptions {
  readonly connection: AberMUDLoginConnection
  readonly engine: Engine<{ readonly session: Session; readonly raw: string }>
  readonly adapter: AberMUDAdapter
  /** Called once login succeeds, so a caller can do whatever placing a fresh character needs
   * (a starting room, for instance) before ordinary input starts flowing to it. */
  readonly onLoggedIn?: (character: EntityId, session: Session) => void
  /** Called once, synchronously, right after ordinary game input is submitted via
   * `engine.receive(...)` -- `receive` only submits, so whatever actually owns running the
   * `Runtime` (a server-owned driver in production; a test's own `engine.runtime.drain()`) does so
   * here, promptly, in the same turn the line was received rather than racing back to some later
   * call site. Omitted, nothing executes automatically, matching `receive()`'s own contract. */
  readonly kick?: () => void
}

type Stage = "name" | "password" | "authenticating" | "playing"

/**
 * Starts the login flow on a freshly accepted `connection`: prompts for a name, then a password
 * with the client's local echo suppressed for it, authenticates, and on success opens a
 * `Session` and switches to routing lines through `engine.receive`. On a failed authentication,
 * reprompts for a name rather than closing the connection.
 */
export function runAberMUDLogin(options: AberMUDLoginOptions): void {
  new LoginFlow(options).start()
}

class LoginFlow extends Base {
  readonly #connection: AberMUDLoginConnection
  readonly #engine: Engine<{ readonly session: Session; readonly raw: string }>
  readonly #adapter: AberMUDAdapter
  readonly #onLoggedIn?: (character: EntityId, session: Session) => void
  readonly #kick?: () => void

  #stage: Stage = "name"
  #name = ""
  #session: Session | undefined
  /** Set in `#onClose`; guards every post-async write so a disconnected connection never receives
   * output generated by an in-flight authenticate/login call. */
  #closed = false

  constructor(options: AberMUDLoginOptions) {
    super()
    this.#connection = options.connection
    this.#engine = options.engine
    this.#adapter = options.adapter
    this.#onLoggedIn = options.onLoggedIn
    this.#kick = options.kick
  }

  start(): void {
    this.#connection.write("Name: ")
    this.#connection.onLine(raw => this.#onLine(raw))
    this.#connection.onClose(() => this.#onClose())
  }

  #onLine(raw: string): void {
    if (this.#stage === "playing") {
      if (!isDefined(this.#session)) {
        // Unreachable: `session` is always set before `stage` becomes "playing". Guarded so a
        // future refactor that breaks that invariant fails loudly instead of dereferencing
        // `undefined`.
        throw new Error("Reached playing stage without an open session")
      }
      this.#engine.receive({ session: this.#session, raw })
      // `receive` only submits; running the Runtime is whatever `kick` was given, the transport
      // loop's own job, not this flow's. See `AberMUDLoginOptions.kick`'s own doc comment.
      this.#kick?.()
      return
    }

    if (this.#stage === "name") {
      this.#name = raw.trim()
      this.#stage = "password"
      this.#connection.setEcho(false)
      this.#connection.write("Password: ")
      return
    }

    if (this.#stage === "authenticating") {
      // `authenticate` is async; nothing stops another line arriving before it resolves, and a
      // network connection can't be assumed to behave like an interactive client that waits for
      // its own prompt. Dropped rather than queued: there is nothing yet to do with a line sent
      // before the account it would apply to is even decided, and a real client sends one at a
      // time anyway.
      return
    }

    // stage === "password"
    this.#stage = "authenticating"
    const password = raw
    // The client's own local echo was off for that line, so nothing moved the cursor to a new
    // line the way it normally would on Enter; move it now, before anything else is written.
    this.#connection.write("\r\n")
    void this.#authenticate(password)
  }

  async #authenticate(password: string): Promise<void> {
    let principal: Awaited<ReturnType<AberMUDAdapter["authenticate"]>>
    try {
      principal = await this.#adapter.authenticate(this.#name, password)
    } catch (error) {
      this.log.error({ err: error }, "Authentication threw unexpectedly")
      this.#connection.setEcho(true)
      if (!this.#closed) {
        this.#connection.write("Login failed. Please try again.\r\n")
        this.#stage = "name"
        this.#connection.write("Name: ")
      }
      return
    }

    // Echo stays suppressed for the whole authentication call, not just while the password was
    // being typed: restoring it earlier would be correct for typing but leaves it off for no
    // reason during whatever `authenticate` itself takes to resolve.
    this.#connection.setEcho(true)

    if (this.#closed) return

    if (!isDefined(principal)) {
      this.#connection.write("Login incorrect.\r\n")
      this.#stage = "name"
      this.#connection.write("Name: ")
      return
    }

    const newSession: Session = {
      id: sessionId(this.#connection.id),
      principalId: principal,
      // The renderer lives on the session, so the engine and adapter never see the wire. QUIT
      // sends its own confirmation through this same channel; closing the connection after
      // writing it is this composition's job, not the handler's -- the handler has no
      // reference to `connection`, only to `session`, and never should. KILL's own death
      // sequence (`"killed"`, `"victim"`) closes the same way -- `crapup()`'s forced disconnect
      // in the source, distinct from QUIT's voluntary one, but the same boundary either way.
      send: message => {
        const output = message as AberOutput
        this.#connection.write(`${renderOutput(output)}\r\n`)
        if (output.kind === "quit" && output.perspective === "actor") {
          this.#connection.close()
        }
        if (output.kind === "killed" && output.perspective === "victim") {
          this.#connection.close()
        }
      },
    }
    this.#session = newSession
    this.#engine.sessions.open(newSession)

    let character: EntityId
    try {
      character = await this.#adapter.login(this.#engine.world, newSession, this.#name, 0)
    } catch (error) {
      this.log.error({ err: error }, "Character login threw unexpectedly")
      this.#engine.sessions.disconnect(newSession.id)
      this.#session = undefined
      if (!this.#closed) {
        this.#connection.write("Login failed. Please try again.\r\n")
        this.#stage = "name"
        this.#connection.write("Name: ")
      }
      return
    }

    if (this.#closed) {
      // Connection dropped while login was in flight: clean up the session that was opened.
      this.#engine.sessions.disconnect(newSession.id)
      return
    }

    this.#stage = "playing"
    try {
      this.#onLoggedIn?.(character, newSession)
    } catch (error) {
      this.log.error({ err: error }, "Post-login initialization failed")
      this.#engine.sessions.disconnect(newSession.id)
      this.#session = undefined
      if (!this.#closed) {
        this.#connection.write("Login failed. Please try again.\r\n")
        this.#stage = "name"
        this.#connection.write("Name: ")
      }
      return
    }
    this.#connection.write("ready\r\n")
  }

  #onClose(): void {
    this.#closed = true
    if (isDefined(this.#session)) {
      this.#engine.sessions.disconnect(this.#session.id)
    }
  }
}
