#!/usr/bin/env bash

# -----------------------------------------------------------------------------
# Template Utility Functions for Workspace/Package Generation
# -----------------------------------------------------------------------------
# Requires: _validation.sh (validate, error, etc.), _helpers.sh (path utils)
source "$(dirname "$0")/lib/_validation.sh"
source "$(dirname "$0")/lib/_helpers.sh"

# -----------------------------------------------------------------------------
# Type-Only Detection
# -----------------------------------------------------------------------------
# Returns true if the package is types-only (by name convention).
is_types_only() {
  local pkg_id="$1"
  # Customize detection logic as needed
  [[ "$pkg_id" == *types* ]]
}

# -----------------------------------------------------------------------------
# Test Directory Generation
# -----------------------------------------------------------------------------
# Creates src/test/ for non-types-only packages.
create_test_dir_if_needed() {
  local pkg_dir="$1"
  local pkg_id="$2"
  if ! is_types_only "$pkg_id"; then
    mkdir -p "$pkg_dir/src/test"
  fi
}

# -----------------------------------------------------------------------------
# Vite Config Generation
# -----------------------------------------------------------------------------
# Creates a blank vite.config.ts for non-types-only packages.
create_vite_config_if_needed() {
  local pkg_dir="$1"
  local pkg_id="$2"
  if ! is_types_only "$pkg_id"; then
    cat >"$pkg_dir/vite.config.ts" <<EOF
// Vite config for $pkg_id
export default {}
EOF
  fi
}

# -----------------------------------------------------------------------------
# package.json Generation
# -----------------------------------------------------------------------------
# Creates a package.json file with build/lint scripts and devDependencies.
# Adds test script and vitest only for non-types-only packages.
create_package_json() {
  # Validate arguments
  validate "[[ -z \"${1:-}\" || -z \"${2:-}\" ]]" "Missing required arguments. Usage: $0 <name> <area: packages|apps> <namespace>"

  local pkg_dir="$1"
  local pkg_json="$pkg_dir/package.json"

  validate "[ -f \"$pkg_json\" ]" "package.json already exists at $pkg_json"

  # Extract dependency versions from root
  local ts_version
  ts_version="$(jq -r '.devDependencies.typescript' "$BASE_DIR/package.json")"

  local fest_version
  fest_version="$(jq -r '.devDependencies["type-fest"]' "$BASE_DIR/package.json")"

  # Create base package.json
  jq -n --arg pkg_id "$2" --arg ts_version "$ts_version" --arg fest_version "$fest_version" '
  {
    "name": $pkg_id,
    "version": "0.1.0",
    "type": "module",
    "main": "./dist/index.js",
    "types": "./dist/index.d.ts",
    "exports": {
      ".": {
        "import": "./dist/index.js",
        "default": "./dist/index.js",
        "types": "./dist/index.d.ts"
      }
    },
    "scripts": {
      "build": "tsc --project tsconfig.json",
      "lint": "eslint . --ext .ts,.tsx"
    },
    "devDependencies": {
      "typescript": $ts_version,
      "type-fest": $fest_version
    }
  }
  ' >"$pkg_json"

  # Add test script and vitest for non-types-only packages
  if ! is_types_only "$2"; then
    jq '.scripts.test = "vitest run" | .devDependencies.vitest = "^1.0.0"' "$pkg_json" >"$pkg_json.tmp" && mv "$pkg_json.tmp" "$pkg_json"
  fi
}

# -----------------------------------------------------------------------------
# tsconfig.json Generation
# -----------------------------------------------------------------------------
# Creates a tsconfig.json file with base config and extends injected.
create_tsconfig_json() {
  validate "[[ -z \"${1:-}\" ]]" "Missing required argument: package directory."

  local pkg_dir="$1"
  local tsconfig_path="$pkg_dir/tsconfig.json"

  validate "[ -f \"$tsconfig_path\" ]" "tsconfig.json already exists at $tsconfig_path"

  # Write base tsconfig.json
  cat >"$tsconfig_path" <<EOF
{
  "compilerOptions": {
    "baseUrl": ".",
    "paths": {
      "@/*": ["src/*"]
    }
  },
  "include": ["index.ts"],
  "exclude": ["node_modules", "dist"]
}
EOF

  # Inject extends field using jq
  local extends_path
  extends_path=$(get_tsconfig_base_relative_path "$pkg_dir")

  jq --arg extends "$extends_path" '.extends = $extends' "$tsconfig_path" >"$tsconfig_path.tmp" && mv "$tsconfig_path.tmp" "$tsconfig_path"
}

# -----------------------------------------------------------------------------
# README.md Generation
# -----------------------------------------------------------------------------
# Creates a basic README.md for the package.
create_readme() {
  local pkg_dir="$1"
  local pkg_id="$2"
  cat >"$pkg_dir/README.md" <<EOF
# $pkg_id

This is the $pkg_id package generated by the workspace script.
EOF
}
