export { drop, registerDrop } from "./drop.ts"
export { exits, registerExits } from "./exits.ts"
export { get, registerGet } from "./get.ts"
export { inventory, registerInventory } from "./inventory.ts"
export { describeRoom, look, registerLook, resolveActor, roomOf } from "./look.ts"
export { move, registerMove, resolveDirection } from "./move.ts"
export { findObjectAt } from "./objects.ts"
export { quit, registerQuit } from "./quit.ts"
export { registerSave, save } from "./save.ts"
export { registerSay, say } from "./say.ts"
export { registerTell, tell } from "./tell.ts"
export { registerWho, who } from "./who.ts"
